trinodb/aws-proxy

README.md, pom.xml, trino-s3-proxy/pom.xml, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/TrinoS3ProxyServerModule.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/credentials/CredentialsController.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/credentials/SigningController.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/credentials/SigningMetadata.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/StreamingResponseHandler.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyClient.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyResource.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestingCredentialsController.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestingTrinoS3ProxyServer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestingTrinoS3ProxyServerModule.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/credentials/TestSigningController.java
See ReadMe for details: https://github.com/trinodb/s3-proxy/blob/jordanz/initial-proxied-request/README.md
E.g.
```shell
~/dev/starburst/trino-s3-proxy (jordanz/initial-proxied-request)$ aws --endpoint-url http://localhost:53893/api/v1/s3Proxy/s3 s3 ls s3://galaxy-cur/     
PRE demo/
PRE dev/
PRE prod/
PRE staging/
2024-05-16 11:41:31          4 aws-programmatic-access-test-object
```
Closes #8
Closes #10
=> Beginnings of S3 request proxying

README.md, pom.xml, trino-s3-proxy/pom.xml, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/TrinoS3ProxyServerModule.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/S3EndpointBuilder.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyClient.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/LocalServer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestProxiedRequests.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/ManagedS3MockContainer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingCredentialsController.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingS3ClientProvider.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingS3EndpointBuilder.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingTrinoS3ProxyServer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingTrinoS3ProxyServerModule.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/harness/BuilderFilter.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/harness/TrinoS3ProxyTest.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/harness/TrinoS3ProxyTestExtension.java
- JUnit framework for easily instantiating tests
- Injection of Adobe Mock S3 server
- Injection of configured S3Client
Closes #4
=> Introduce testing harness

trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/credentials/Signer.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/credentials/SigningController.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyClient.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestProxiedRequests.java
Some ad hoc testing revealed a few bugs.
- Use `now()` when making the real request
- Signer must not double encode URLs
=> A few bug fixes

trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/StreamingResponseHandler.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyClient.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/rest/HangingResource.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/rest/TestHangingStreamingResponseHandler.java
The latch that was used wasn't doing anything. Remove it with the understanding the configured timeouts for the HttpClient and Jersey/Glassfish will handle any timeout issues.
Added a test to prove that timeouts are applied.
FYI - I tested this locally with a 32MB S3 file and it seems to work well.
=> Refine and test StreamingResponseHandler

trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/LocalServer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/ContainerS3Facade.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/ManagedS3MockContainer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingConstants.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingRemoteS3Facade.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingS3ClientProvider.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingTrinoS3ProxyServer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/harness/TrinoS3ProxyTestExtension.java
This PR aims to:
**1: Remove the dependency between `TestingRemoteS3Facade` and `ManagedS3MockContainer`:**
The `Testing*` classes (this one and `TestingCredentialsController`) should be agnostic to the implementation and seem designed to provide a way to merely tap into the logic of what the proxy is doing. As such, I think the previous flow of having a `TestingRemoteS3Facade` that calls a delegate is nice.
We can implement the logic to connect this to our `ManagedS3MockContainer` by creating a new module that gets these injected
**2: Stop `TestingS3ClientProvider` from setting up new credentials:**
`TestingS3ClientProvider` was creating a random `emulated` credential and adding it to the credential controller every time it was called. This was IMHO somewhat confusing as we were already …
=> Separate the TestingControllers and our specific implementations of them

trino-s3-proxy/pom.xml, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/TrinoS3ProxyServerModule.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/collections/MultiMapHelper.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/credentials/Signer.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/ParsedS3Request.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyClient.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyConfig.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyResource.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestProxiedAssumedRoleRequests.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestProxiedRequestsToVirtualHostEndpoint.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestProxiedRequestsWithVirtualHostProxy.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestRemoteSessionProxiedRequests.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/credentials/TestAssumingRoles.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingS3ClientProvider.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingTrinoS3ProxyServer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingUtil.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/harness/TrinoS3ProxyTest.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/harness/TrinoS3ProxyTestCommonModules.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/harness/TrinoS3ProxyTestExtension.java
Closes #19 
This PR also goes slightly into #37 , by creating an `S3RequestInformation` record - if @ragnard and @mosiac1 are happy with this choice, I'm glad to add the remaining fields and make the signer use it too.
=> Support serving of Virtual Host requests

trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/HashCheckInputStream.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyClient.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/signing/Signer.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/signing/SigningContext.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/TestGenericRestRequests.java
For AWS requests that aren't chunked and that have a `x-amz-content-sha256` header, validate the hash of the input stream.
Closes #70
=> Validate the hash for standard, non-chunked input streams

trino-s3-proxy-spi/src/main/java/io/trino/s3/proxy/spi/rest/ParsedS3Request.java, trino-s3-proxy-spi/src/main/java/io/trino/s3/proxy/spi/rest/Request.java, trino-s3-proxy/pom.xml, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/TrinoS3ProxyServerModule.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/credentials/CredentialsController.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/RequestBuilder.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/RequestLoggerController.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/RequestLoggingSession.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/StreamingResponseHandler.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3ProxyClient.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/rest/TrinoS3Resource.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/signing/InternalSigningController.java, trino-s3-proxy/src/main/java/io/trino/s3/proxy/server/signing/Signer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/rest/HangingResource.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/signing/TestSigningController.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/TestingTrinoS3ProxyServer.java, trino-s3-proxy/src/test/java/io/trino/s3/proxy/server/testing/containers/DockerAttachUtil.java
TODO - add complete telemetry system
Adds controller that logs requests and allows for eventual admin
API that can return recent request info
Relates to #25
=> 01 - Add request logging mechanism

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RequestFilter.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RequestLoggerController.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/StreamingResponseHandler.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoS3Resource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoStsResource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/signing/InternalSigningController.java
Remove the burden of allocating and managing common objects from handlers, endpoints, etc. and use a Request filter to do all the work. This has the additional benefit of adding security to every request without the need for developer discipline.
Note: you can see how this improves on the request logging PR in that the creation and closing of the request logging session is now auto-managed.
=> 03 - Inject and manage common objects via a request filter

trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/credentials/EmulatedAssumedRole.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoStsResource.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/AbstractTestStsRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/TestAssumingRoles.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingCredentialsRolesProvider.java
Remove the duplicated session field in `EmulatedAssumedRole`. This record already contains a `Credential`, which itself has a session token.
=> Remove duplicated session field

pom.xml, trino-aws-proxy/pom.xml, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/AwsChunkedInputStream.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoS3ProxyClient.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestAwsChunkedInputStream.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/signing/TestingChunkSigningSession.java
Rewrite of `AwsChunkedInputStream` for simplicity/clarity
~~Added `ReadAheadInputStream` which buffers a portion of a delegate input stream which is assumed to be an `AwsChunkedInputStream`. The purpose of this is to catch an edge case with the final chunk. By the time the final chunk
signature is verified, the bytes of the chunk will already be sent to the remote server and, thus, it's too late to prevent it. By reading ahead, the final chunk will get validated before the bytes are sent to the remote.~~
When the end of a chunk is reached it reads the next chunk's header. This ensures we don't send the final bytes of a request before they've been validated against the signature. i.e. the final chunk's signature cannot be validated
until the final chunk has been read. But, without this …
=> Rewrite of AWS Chunked support

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/signing/InternalChunkSigningSession.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/AbstractTestProxiedRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestGenericRestRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestPresignedRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/signing/TestingChunkSigningSession.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingUtil.java
This enables us to add more thorough testing for #101 and to deal with the issues discussed in #105 (where it is possible for a chunk with invalid size to cause the proxy to skip signature verification)
=> Add more thorough tests for aws-chunked

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyConfig.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoAwsProxyConfig.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoS3Resource.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/AbstractTestStsRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/LocalServer.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestGenericRestRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestPresignedRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestProxiedAssumedRoleRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestProxiedEmulatedAndRemoteAssumedRoleRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestProxiedRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestProxiedRequestsWithEmptyPath.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestRemoteSessionProxiedRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestStsRequestsWithEmptyPath.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestStsRequestsWithPath.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/TestAssumingRoles.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingS3ClientProvider.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingTrinoAwsProxyServer.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/containers/MetastoreContainer.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/containers/PySparkContainer.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/harness/TrinoAwsProxyTestCommonModules.java
Better reflect its usage
Note: no code changes. Just renaming/moving.
=> Rename and move TrinoS3ProxyConfig to TrinoAwsProxyConfig

pom.xml, trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/security/S3DatabaseSecurityFacade.java, trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/security/SecurityResponse.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoS3ProxyClient.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/security/S3DatabaseSecurityController.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/security/S3SecurityController.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestDatabaseSecurity.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestS3SecurityController.java
With the latest Java, we can have a more modern definition for `SecurityResponse` as a sealed hierarchy with explicit Success and Failure types. This makes it easier to understand and use properly.
Java is indistinguishable from Scala :D
=> Improve the design of `SecurityResponse`

000-temp-trino-aws-proxy/pom.xml, 000-temp-trino-aws-proxy/src/main/java/org/eclipse/jetty/client/transport/HttpSender.java, pom.xml, trino-aws-proxy/pom.xml
https://github.com/jetty/jetty.project/issues/11841 has an NPE when using 100-Continue. This hack is a workaround.
- Create a new module that generates a JAR that will sort first in the classpath
- Put a hacked version of Jetty's `HttpSender` in this module that has a fix
- The Java classloader will load this version of the class first, thus working around the problem
This hack should be removed as soon as possible
=> Temporary fix for https://github.com/jetty/jetty.project/issues/11841

trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/containers/MetastoreContainer.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/containers/S3Container.java
The Metastore is a trusted resource. It doesn't need to go through the proxy. Change the test container to connect directly to the object store.
This will be needed for future work with presigned URL redirects.
=> Have metastore connect directly to remote

pom.xml, trino-aws-proxy-spark3/pom.xml, trino-aws-proxy-spark3/src/main/java/io/trino/aws/proxy/spark3/PresignAwareAmazonS3.java, trino-aws-proxy-spark3/src/main/java/io/trino/aws/proxy/spark3/TrinoAwsProxyS3ClientFactory.java, trino-aws-proxy-spark3/src/main/java/io/trino/aws/proxy/spark3/TrinoAwsProxyS3ClientSigil.java, trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/signing/SigningContext.java, trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/signing/SigningController.java, trino-aws-proxy/pom.xml, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyConfig.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/S3PresignController.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/StreamingResponseHandler.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoS3ProxyClient.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/signing/InternalSigningController.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/signing/Signer.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/signing/SigningHeaders.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestGenericRestRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestPySparkSql.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/HangingResource.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestPresigningHeaders.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/signing/TestSigningController.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingS3PresignController.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingTrinoAwsProxyServerModule.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingUtil.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/containers/PySparkContainer.java
Support proxy generated bypass pre-signed URLs
Add support generating pre-signed URLs for get/put object. These
are generated (if the config setting is `true`) on HEAD object
requests and are returning in custom response headers: 
`X-Trino-Pre-Signed-Url-Get` and `X-Trino-Pre-Signed-Url-Put`
Introduce Spark 3 module
Add Spark 3 module which provides an AWS S3 client for Spark/Hadoop
that uses pre-signed URLs to get/put objects.
For Spark 3, add this config:
```
spark.hadoop.fs.s3a.s3.client.factory.impl=io.trino.aws.proxy.spark3.TrinoAwsProxyS3ClientFactory
```
For Hadoop, add this config:
```
fs.s3a.s3.client.factory.impl=io.trino.aws.proxy.spark3.TrinoAwsProxyS3ClientFactory
```
=> Spark 3 support

trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/credentials/Credentials.java, trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/credentials/Identity.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/file/FileBasedCredentialsProviderModule.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestGenericRestRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/file/TestFileBasedCredentialsProvider.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingIdentity.java, trino-aws-proxy/src/test/resources/credentials.json
The Identity entity is modelled as an interface and embedded into the Credentials class. 
Ideally, teams implement their own version of Identity and provide custom deserialization logic.
=> Added identity to Credentials

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/AwsChunkedInputStream.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoS3ProxyClient.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestGenericRestRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestAwsChunkedInputStream.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/signing/TestingChunkSigningSession.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingUtil.java
Closes #102
Ensure we never return `x-amz-decoded-content-length` bytes without having verified the signatures.
This should protect us from:
- Chunks overreporting their size so that we send `x-amz-decoded-content-length` before validating the signature (as the proxy did not know the chunk had finished)
- Chunks containing more data than they report
- Mismatched declared and actual content lengths
=> Add strict signature validation of aws-chunked streams

trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/security/opa/OpaRequest.java, trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/security/opa/OpaS3SecurityMapper.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/security/opa/ForOpa.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/security/opa/OpaS3SecurityConfig.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/security/opa/OpaS3SecurityFacadeProvider.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/security/opa/OpaS3SecurityModule.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestDatabaseSecurity.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestOpaSecurity.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestPySparkSql.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestPySparkSqlV4.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingTrinoAwsProxyServer.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/containers/OpaContainer.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/harness/TrinoAwsProxyTestCommonModules.java
Security decisions are forwarded to an OPA server. Users must
provide a mapping from possible table, request, action, etc.
into an input document which is sent to OPA.
=> Support for OPA policy security

trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingCredentialsRolesProvider.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/containers/S3Container.java
Before this PR, there was no way to ensure that the proxy was in fact
using a session to talk to Minio.
This PR changes the Minio policy configured
in the S3 container to only allow `policyUserCredential` access to S3 if using temporary credentials
=> Improve tests for remote session credentials

trino-aws-proxy/pom.xml, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/http/ForHttpCredentialsProvider.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/http/HttpCredentialsModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/http/HttpCredentialsProvider.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/http/HttpCredentialsProviderConfig.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/http/TestHttpCredentialsProvider.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/http/TestHttpCredentialsProviderConfig.java
The Http credentials provider can be used to fetch the remote credentials and identity from a HTTP service
=> Add http credentials provider

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RequestBuilder.java
We should be using the Jetty URI as the source of truth as Jetty will sanitise the Host header value and process any `X-Forwarded-` headers if present.
=> Use host from Jetty provided URI instead of Host header

README.md, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/http/HttpCredentialsProvider.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/http/HttpCredentialsProviderConfig.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/http/TestHttpCredentialsProvider.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/http/TestHttpCredentialsProviderConfig.java
Added headers to be sent as part of the request in the http credentials provider.
Added a couple of tests to check if the header is working is properly
=> Added headers to http credentials provider

trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestOpaSecurity.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/containers/OpaContainer.java
There are issues running the TestContainers-OpaContainer in a dockerized environment. So, I've made a change to use the OPA host instead of localhost
=> Add opa container host

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/StreamingResponseHandler.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/AbstractTestProxiedRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestProxiedErrorResponses.java
Reading a missing bucket/key will result in a 500 with the error "Insufficient content written 0 < x" (where X is a the expected content size) which seems to be a Jetty error.
The aws-proxy correctly logs that the response from MinIO has status `404` and the `Content-Length` header is set. With a breakpoint I confirmed that the response from MinIO has the same size as `Content-Length`, so I'm not sure why Jetty doesn't get any content.
Will continue investigating.
=> Return proxied response body for all status codes

trino-aws-proxy/pom.xml, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/ErrorResponse.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RequestFilter.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/ThrowableMapper.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestDatabaseSecurity.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/DelegatingCredentialsProvider.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/plugin/exception/TestCredentialsProviderExceptionPropagation.java
We noticed a regression in our testing suite for internal plugins which seems to be cause by https://github.com/trinodb/aws-proxy/commit/bfbcaf26eeb8aa24b1d27a913e4d991b73ff2d9e, specifically the upgrade from `io.airlift:airlift` version `249` to `266` which bumps the jetty version to `12.0.13`.
The test added in this PR passed on `io.airlift:airlift` version `252`, which would indicate what caused the regression was added in jetty `12.0.12`.
The root cause is that a `RequestLoggerController` has unclosed sessions when the Airlift Boostrap lifecycle is getting closed. 
This is because runtime exceptions (that do not inherit from `WebApplicationException`) thrown during request processing (here thrown in the credentials provider plugin, but anywhere works really) causes jetty to not call …
=> Return XML formatted error messages

trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/credentials/http/TestHttpCredentialsProvider.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestProxiedErrorResponses.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingHttpCredentialsProviderServlet.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingUtil.java
The refactor allows reusing of classes for custom implementations of the HTTP Credentials Provider
=> Refactor TestHttpCredentialsProvider

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyConfig.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/NodeStatus.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/ParamProvider.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/ResourceSecurity.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/ResourceSecurityDynamicFeature.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/SecurityFilter.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoLogsResource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoS3Resource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoStatusResource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoStsResource.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestStatusRequests.java
Address https://github.com/trinodb/aws-proxy/issues/157.
Default to path `/api/v1/s3Proxy/status`, returns aws-proxy status.
Refactor `SigningServiceType` binding to used annotation.
=> Add status resource with public access

trino-aws-proxy/pom.xml, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServer.java
This exposes JMX metrics at `/metrics`
=> Add Airlift JMX modules

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RequestLoggerController.java
There seems issues with threads on this line in aws-proxy - https://github.com/trinodb/aws-proxy/blob/main/trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RequestLoggerController.java#L307
Its using [EvictingQueue](https://guava.dev/releases/19.0/api/docs/com/google/common/collect/EvictingQueue.html) which is not thread-safe.
```
java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:361)\n\tat 
java.base/java.util.ArrayDeque.remove(ArrayDeque.java:522)\n\tat 
com.google.common.collect.EvictingQueue.add(EvictingQueue.java:111)\n\tat 
io.trino.aws.proxy.server.rest.RequestLoggerController.logAndClear(RequestLoggerController.java:307)\n\tat 
io.trino.aws.proxy.server.rest.RequestLoggerController.internalNewRequestSession(RequestLoggerController.java:225)\n\tat …
```
=> Fix RequestLoggerController concurrency issues

trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/remote/RemoteUriFacade.java, trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/signing/SigningServiceType.java, trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/signing/SigningTrait.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyConfig.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/CredentialsController.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/credentials/CredentialsModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RequestLoggerConfig.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RequestLoggerController.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/ResourceSecurity.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/ResourceSecurityDynamicFeature.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/RestModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoLogsResource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoS3Resource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoStatusResource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/TrinoStsResource.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/signing/Signer.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/signing/Signers.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestGenericRestRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestHttpChunked.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestRequestLoggerController.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/signing/TestSigningController.java
Abstract RemoteS3Facade's `remoteUri()` into a new interface
that can be used/injected independently of S3 implementations.
Move the Request logging config into separate config class
Abstract new static methods so portions of module can be used in other contexts
=> Refactor to support Glue protocol (separate PR)

pom.xml, trino-aws-proxy-glue/README.md, trino-aws-proxy-glue/pom.xml, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/TrinoGlueConfig.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/TrinoGlueModule.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/TrinoGluePlugin.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/TrinoStandaloneGlueModule.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/handler/GlueRequestHandler.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/handler/GlueRequestHandlerBinding.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/GlueDeserializer.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/GlueResourceSecurity.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/GlueSerializer.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/ModelLoader.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/ParsedGlueRequest.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/SerializerCommon.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/TrinoGlueResource.java, trino-aws-proxy-glue/src/main/resources/META-INF/services/io.trino.aws.proxy.spi.plugin.TrinoAwsProxyServerPlugin, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestGlueBase.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestGlueInS3Proxy.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestGlueStandalone.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestingCredentialsProvider.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestingGlueContext.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestingGlueRequestHandler.java
New module that implements a Glue REST API endpoint allowing Glue proxying/emulation.
- Adds serializers/deserializers for all Glue models
- Glue REST endpoint that marshals request payloads
- Injectable request handler
- Could be the basis of a Glue proxy, though this isn't implemented currently
- Can be run as a standalone Glue endpoint handler
- Can be add Glue endpoint to AWS S3 proxy as standard plugin
ReadMe: https://github.com/trinodb/aws-proxy/blob/jordanz/glue/trino-aws-proxy-glue/README.md
=> Introduce Glue protocol module

trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestProxiedErrorResponses.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingUtil.java
Also, use bespoke S3 client for testing
=> Bind testing server to 0.0.0.0

trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/GlueDeserializer.java, trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/SerializerCommon.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestGlueBase.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestingGlueRequestHandler.java
Previous implementation of GlueDeserializer wasn't handling nested SDK objects. Change to deserializing field by field to manage this.
Added a test with a complex model.
Fixes https://github.com/trinodb/aws-proxy/issues/179
=> Need to deserialize field by field

trino-aws-proxy-glue/src/main/java/io/trino/aws/proxy/glue/rest/GlueDeserializer.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestGlueBase.java, trino-aws-proxy-glue/src/test/java/io/trino/aws/proxy/glue/TestingGlueRequestHandler.java
Recent change to `GlueDeserializer` should have used Generic types and not raw types. This showed when attempting to deserialize, for example, collections.
Fixes https://github.com/trinodb/aws-proxy/issues/181
=> Use generic types for glue deserialization

trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestProxiedErrorResponses.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingUtil.java
Changes added in https://github.com/trinodb/aws-proxy/pull/172 meant to fix an issue with the IP `createTestingHttpServer` binds on accidentally broke this test
=> Revert changes to TestProxiedErrorResponses

trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/AwsChunkedInputStream.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/HashCheckInputStream.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/rest/StreamingResponseHandler.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestGenericRestRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/rest/TestAwsChunkedInputStream.java
Currently the proxy handles most streaming issues due to mismatch between declared content length and uploaded content length as INTERNAL_ERRORs, except for when it's a STANDARD or W3C_CHUNKED and uploaded > content length, then this is handled as UNAUTHORIZED.
This PR is suggesting handle all of the above as BAD_REQUEST.
=> Handle streaming exceptions as bad requests instead of internal errors

trino-aws-proxy-spi/src/main/java/io/trino/aws/proxy/spi/remote/RemoteS3Connection.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyPluginValidatorModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/TrinoAwsProxyServerModule.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/remote/DefaultRemoteS3Module.java, trino-aws-proxy/src/main/java/io/trino/aws/proxy/server/remote/RemoteS3ConnectionController.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestProxiedEmulatedAndRemoteAssumedRoleRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestProxiedRequestsToVirtualHostEndpoint.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestRemoteSessionProxiedRequests.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingRemoteS3Facade.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/TestingTrinoAwsProxyServer.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/testing/harness/TrinoAwsProxyTestCommonModules.java
Replace the RemoteS3Facade plugin type with a RemoteS3FacadeFactory that creates RemoteS3Facade instances based on Map<String, String> configs.
Add RemoteS3FacadeManager to create the default RemoteS3Facade from configs in `remote-s3-facade.properties`.
=> Handle RemoteS3Facade dynamic creation in RemoteS3ConnectionController

trino-aws-proxy-spark3/src/main/java/io/trino/aws/proxy/spark3/PresignAwareAmazonS3.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestDatabaseSecurity.java, trino-aws-proxy/src/test/java/io/trino/aws/proxy/server/TestPySparkSql.java
If present, the range parameter from GetObjectRequest should be added to PresignedUrlDownloadRequest, so that the client gets the expected bytes.
=> Respect range parameter for getObject in presign aware S3 clients
